/**
 * Generates a clean CODEBASE_MAP.md file from analysis results.
 */
function generateMarkdown(projectName, analysisResults, fileTree) {
  const now = new Date().toLocaleString();
  const totalFiles = Object.values(fileTree).reduce((sum, files) => sum + files.length, 0);
  const totalFolders = Object.keys(fileTree).length;
 
  const lines = [];
 
  // Header
  lines.push(`#  Codebase Map — ${projectName}`);
  lines.push('');
  lines.push(`> Auto-generated by [RepoLens](https://github.com/Harkiratcodess/Repo-lens) on ${now}`);
  lines.push(`> **${totalFiles} files** across **${totalFolders} folders** analyzed.`);
  lines.push('');
  lines.push('---');
  lines.push('');
 
  // Quick index at the top (clickable links to each folder section)
  lines.push('##  Folder Index');
  lines.push('');
  for (const folderPath of Object.keys(analysisResults).sort()) {
    const anchor = folderPath.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase();
    const label = folderPath === '.' ? '/ (root)' : folderPath;
    lines.push(`- [${label}](#${anchor})`);
  }
  lines.push('');
  lines.push('---');
  lines.push('');
 
  // Folder-by-folder breakdown
  lines.push('##  File Breakdown');
  lines.push('');
 
  const sortedFolders = Object.keys(analysisResults).sort((a, b) => {
    // Root first, then alphabetical
    if (a === '.') return -1;
    if (b === '.') return 1;
    return a.localeCompare(b);
  });
 
  for (const folderPath of sortedFolders) {
    const folderSummaries = analysisResults[folderPath];
    const files = fileTree[folderPath] || [];
    const anchor = folderPath.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase();
    const label = folderPath === '.' ? '/ (project root)' : `📁 ${folderPath}`;
 
    lines.push(`### ${label}`);
    lines.push(`<a name="${anchor}"></a>`);
    lines.push('');
 
    if (files.length === 0) {
      lines.push('_No readable files found._');
      lines.push('');
      continue;
    }
 
    // Table: File | Purpose | Size
    lines.push('| File | What it does | Size |');
    lines.push('|------|-------------|------|');
 
    for (const file of files.sort((a, b) => a.name.localeCompare(b.name))) {
      const summary = folderSummaries[file.name] || '_Not analyzed_';
      // Escape pipe chars in summary to not break the table
      const safeSummary = summary.replace(/\|/g, '\\|');
      lines.push(`| \`${file.name}\` | ${safeSummary} | ${file.sizeKB} KB |`);
    }
 
    lines.push('');
  }
 
  // Footer tip
  lines.push('---');
  lines.push('');
  lines.push('## How to use this map');
  lines.push('');
  lines.push('1. **Found a bug?** Search this file for keywords from the issue title to find the right folder fast.');
  lines.push('2. **Adding a feature?** Look for the folder that handles similar functionality.');
  lines.push('3. **Confused by a file?** The table above tells you its job at a glance.');
  lines.push('4. **Map is outdated?** Run `RepoLens: Analyze Codebase` again — unchanged files load from cache instantly.');
  lines.push('');
  lines.push('>  Add `CODEBASE_MAP.md` and `.codemap-cache.json` to your `.gitignore` if this is a personal analysis.');
  lines.push('');
 
  return lines.join('\n');
}
 
module.exports = { generateMarkdown };